include: package:flutter_lints/flutter.yaml

linter:
  # in the example project, we are a bit less strict
  rules:
    use_key_in_widget_constructors: false
    prefer_const_constructors_in_immutables: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false